### ISSUE TITLE
Support for R language

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/runner-image#59]
Now that R is supported in pre-commit, it should not take the world to make it work on pre-comit.ci (gauged from the line diff in #31). Should I follow that PR for an implementation?

**Comment by asottile** [comment]
I'm currently working on making languages easier to add and less impactful to autoscaling -- the current approach of having everything always in the image makes it difficult to be performant.  I'm planning to do something like individual language bundles instead of a monolithic mega-image but I haven't finished the work there.

if you start a PR though it'll still be helpful in the new world, but will likely need some small amount of refactoring

**Comment by lorenzwalthert** [comment]
I looked at the code and I wondered what reasons there were against making one image pre language... Do you have any ETA on that refactoring?

**Comment by asottile** [comment]
one image per language doesn't work -- a pre-commit config may reference many languages

I don't have an ETA at the moment unfortunately

**Comment by asottile** [comment]
ok!  I now have a way for languages to not impact the scaling time

the tl;dr is a language must be exactly two instructions: and `ENV` line which sets up the environment variables for that language, immediately followed by a `RUN` line which does `echo 'lang: ...'`.  there's currently a single example of this for `swift`, I will be porting some of the other languages to be deferred in this way as well to make scaling even faster.  the `RUN` command should install everything into `/opt/${lang}` and basically use that as a prefix environment

let me know if you'd like some help with getting `r` set up in this way!

**Comment by lorenzwalthert** [comment]
Thanks, I filed #80 to propose a concrete implementation. Also, I saw you updated the README to that effect. Maybe it's worth also pointing out there that a test should be added (and how). I followed the Swift example for #80.
